version: '3.8'

volumes:
  backstage-postgres:

services:
  database:
    image: postgres
    volumes:
     -  backstage-postgres:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: backstage_user
      POSTGRES_PASSWORD: backstage_password
      POSTGRES_DB: backstage
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
  

  backstage:
    image: "${TESTING_IMAGE}"
    ports:
      - "7007:7007"
      - "3000:3000"
   
    environment:
      POSTGRES_USER: backstage_user
      POSTGRES_PASSWORD: backstage_password
      POSTGRES_DB: backstage
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
          
    depends_on:
      - database
  


      
      
      
         
