version: '3.8'

volumes:
  backstage-postgres:

services:

  database:

    image: postgres
    volumes:
      - backstage-postgres:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: backstage_user
      POSTGRES_PASSWORD: backstage_password
      POSTGRES_DB: backstage
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
          
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      retries: 10

  backstage:

    image: ghcr.io/chichicaleb/backstage-portal:9588787880

    ports:
      - "7007:7007"
      - "3000:3000"

    environment:
      POSTGRES_USER: backstage_user
      POSTGRES_PASSWORD: backstage_password
      POSTGRES_DB: backstage
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
          

    depends_on:
      database:
        condition: service_healthy
