version: '3.8'

volumes:
  database-data:

services:

  database:

    image: postgres
    volumes:
      - database-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backstage
      POSTGRES_HOST: database:5432
      POSTGRES_PORT: 5432
          
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      retries: 10

  backstage:

    image: ghcr.io/chichicaleb/backstage:9587466534

    ports:
      - "7007:7007"
      - "3000:3000"

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backstage
      POSTGRES_HOST: database:5432
      POSTGRES_PORT: 5432
          

    depends_on:
      database:
        condition: service_healthy
